## SYNTAX ERRORS : YOU MADE SOME ERRORS IN TYPING THE CODE 
## VALUE ERRORS : WRONG INPUT HAS BEEN PROVIDED TO THE CODE
## USING try: AND except: KEYWORDS 
try :
 x=int(input("WHATS X ?--->"))
 print(x)
 
except ValueError:
  print("WRONG INPUT HAS BEEN PROVIDED")

  ##SOMETIME INDENTATION ERRORS CAN ARRIVE IF PROPER LINES | LIKE THESE ARE NOT IN THEIR PROPER PLACES

## NAME ERROR : YOU ARE DOING SOMETHING THAT IS NOT DEFINED 
## ALSO THIS NEXT CODE GENERATES VALUE ERROR BECAUSE ALTOUGH IT CATCHES THE ERROR THE PRINT FUNCTION IS STILL IN THE USE 
try :
    x=int(input("WHATS x ?---->"))

except ValueError :
 print(" THE PROVIDED INPUT IS INVALID")


print(x)

## TO SOLVE THIS PREVIOUS PROBLEM WE CAN USE LOOP AND ADD CONDITION INSIDE IT
## THE except KEYWORD AUTOMATICALLY SENDS True TO THE CONDITION AND THE LOOP CONTINUES
while True:

 try :
     x=int(input("WHATS x ?---->"))

 except ValueError :
     print(" THE PROVIDED INPUT IS INVALID")

 else :
     break
 
print(f"{x}")