## open IS A KEYWORD IN PYTHON THAT OPENS FOR READING AND WRITING PURPOSES


name=input("what is your name?--->")

## FIRST WE WILL OPEN A TEXT FILE BY USING SYNTAX
## file = open("names.txt","w")
## REMEMBER TO ADD COMMA BETWEEN THE FILE NAME AND THE "w"
## REMEMBER TO USE INVERTED COMMAS FOR BOTH THE FILE NAME AND  THE R AND W
## HERE file IS A VARIABLE THAT STORES A FILE TEMPORARILY
## ALSO open() IS A FUNCTION THAT OPENS THE SPECIFIC FILE ENTERED INSIDE THE INVERTED COMMAS
## HERE "w" SPECIFIES THAT THE FILE OPENED IS FOR WRITING PURPOSE
## IF THE FILE NAME WE ENTERED IS NOT PRESENT THEN AUTOMATICALLY A NEW FILE WILL BE CREATED
## TO MANUALLY CREATE A FILE TYPE code names.txt IN THE TERMINAL
## WE CAN ALSO WRITE "r" TO READ THE FILE 
## IF NO "w" OR "r" IS GIVEN THEN BY DEFAULT IT IS SET TO READ 

file=open("names.txt","w")

## HERE write() FUNCTION INPUTS THE VARIABLE INTO THE FILE 
## HERE WE CANNOT USE append() FUNCTION IT CREATES ERROR BECUASE IT IS NOT USED FOR FILE
file.write(name)

## close() FUNCTION CLOSES THE FILE WE WERE USING
file.close()

## THE PROBLEM WITH THIS CODE IS THAT IT STORES ONLY ONCE THE NEXT TIME WE RUN THE CODE PREVIOUS VALUES ARE GONE