name = input("what's your name????--->")

## HERE "a" IS USED TO APPEND THE NAMES ENTERED WHICH MEANS IT STORES THE NAMES EVEN IF THE FILE IS CLOSED
file=open("names.txt","a")
file.write(name)
file.close()
## BUT THE PROGRAM DOESNT SEPARATE THE ENTERED NAMES WITH SPACE OR SUCH SYNTAX IT JUST CONCATENATES THEM