name=input("NAME--->")
## IN THIS PROGRAM IF THE USER ENTERS THE LAST NAME FIRST THEN WE NEED TO REPLACE IT LIKE THIS
if ", " in name:
    last,first=name.split(", ")

name=f"{first} {last}"
print(f"hello {name} !")

## A|B IS THE SYNTAX THAT IS USED FOR A OR B
## WE CAN GROUP THE ELEMENTS LIKE (....)
## ALSO A NON CAPTURING VERSION COULD BE (?:.....) THIS MEANS WHEN YOU WANT TO REPEATEDLY FIND THE SAME PATTERN INSIDE THE STRING YOU CAN USE THIS 
## EXAMPLE abcabcabc (?:abc)+ WILL BE THE SYNTAX