##  WHEN WE DEFINING A CONDTION OR A VARIABLE INSIDE AN ANOTHER CONDITION TO TIGHTEN UP THE CODE WE USE WALRUS OPERATOR
## :=
## EXTRACTING

## HERE WE WILL TRY TO EXTRACT THE USERNAME FROM THE URL
url=input("URL:").strip()
print(url)

## ANOTHER WAY OF DOING THIS CAN BE USING THE REPLACE FUNCTION
## THE SYNTAX FOR REPLACE FUNCTION IS replace("THE WORDS YOU WANT TO REPLACE","THE WORDS YOU WANT TO REPLACE IT WITH")

username=url.replace("https://twitter.com/","")
print(f"username= {username}")

## AN ANOTHER WAY OF DOING THIS COULD BE USING removeprefix() FUNCTION
## THIS FUNCTION IS USED TO REMOVE PREFIXES FROM STRINGS. IF THAT PARTICULAR STRING IS NOT PRESENT OR MORE PREFIXES ARE PRESEN THAN ORIGINAL STRING IS RETURNED
username=url.removeprefix("https://twitter.com/")
print(username)