## TO IMPORT THE FUNCTION FROM OUR PREVIOUS FILE THE SYNTAX IS 
## from FILE import FUNCTION
## REMEMBER THAT NO BRACKETS ARE USED WHILE IMPORTING
## REMEMBER THAT THE FILE NAME SHOULD NOT CONTAIN ANY SPACES

from library29 import hello
import sys
if len(sys.argv)==2:
    hello(sys.argv[1])

## BUT THIS SYNTAX CAUSES AN ERROR TO OCCUR BECAUSE THE FILE FROM WHICH WE HAVE IMPORTED THE FUNCTION ALSO HAS A MAIN FUNCTION 
## TO RESOLVE THIS WE ADD A NEW SYNTAX BEFORE CALLING main() THAT IS
## if __name__=="__main__": IN THE FILE FROM WHICH WE ARE IMPORTING THE FUNCTION
