## LIBRARIES 
## LIBRARIES OR MODULES CAN BE USED TO REUSE A WRITTEN CODE IN DIFFERENT PROJECTS 

## random (library)
## import IS A KEYWORD USED TO IMPORT A LIBRARY IN A PROGRAM
## random.choice(seq) IS A FUNCTION THAT CHOOSES AN ELEMENT OUT OF THE GIVEN SEQUENCE
## THE seq() REPRESENT THE AREA WHERE ELEMENTS ARE TO BE PROVIDED 

## FLIPPING  A COIN 
## THERE IS NO COLON IN IMPORTING THE MODULES
## THE SYNTAX TO INPUT IN CHOICE IS 
## x=random.choice(["a","b"])
## REMEMBER TO PUT THE SQUARE BRACKETS ALONG WITH SIMPLE BRACKETS
import random

coin=random.choice(["heads","tails"])
print(coin)