## sys LIBRARY
## sys STANDS FOR SYSTEM
## sys.argv[] IS A FUNCTION IN THE SYSTEM LIBRARY
## HERE argv IS A VARIABLE
## THIS FUNCTION DIRECTLY TAKES THE INPUT ENTERED JUST AFTER THE FILE IS RAN OR IS TYPED IN THE TERMINAL TO RUN
## ALSO sys.argv[0] STORES FILE NAME AND sys.argv[1] STORES THE FIRST THING ENTERED AFTER THE FILE NAME
## IF THE FIRST INPUT IS GIVEN USING "HELLO HI" THEN IT WILL TREAT AS ONE AND PRINT THE WHOLE INPUT
## IF WE ARE NOT INPUTING ANYTHING HERE INDEX ERROR WILL OCCUR BECAUSE THE INTERPRETER IS EITHER GOING TOO FAR RIGHT OR TOO FAR LEFT WHICH IS EMPTY
## IN THIS VS CODE THIS MIGHT NOT WORK THE RUN COMMAND AUTOMATICALLY TYPES CODE AND RUNS IT 
## TO RUN IT IN THE FORMAT THAT WAS TAUGHT COPY THE WHOLE ADDRESS THEN RUN IT 

import sys

try :
     print("hello my name is ", sys.argv[1])

except IndexError :
     print("too few arguments")
   