## SINCE WE GENERALLY WANT ALPHABETS NUMBERS AND UNDERSCORE IN OUR EMAIL ADDRESSES WE CAN USE \w INSTEAD PF SETTING THE WHOLE RANGE OF CHARACTERS
import re
email=input("email--->")
if re.search(r"^\w+@\w+\.edu$",email): 
    print("VALID")

else:
    print("invalid")

## ANOTHER TYPES OF SYNTAX THAT CAN BE USED ARE
## \d FOR DECIMAL DIGITS ONLY
## \D FOR NO DECIMAL DIGIT
## \s WHITE SPACE CHARACTER
## \S NOT A WHITE SPACE CHARACTER
## \w WORDS, NUMBERS, AND UNDERSCORE
## \W NOT A WOR
## (\w| ) THE SYNTAX INSIDE THE () SPECIFIES THAT EITHER WORD OR SPACE IS ALLOWED