## STRATEGISED LOOPS
## IN THESE TYPES OF LOOPS WE CAN ENSURE THAT THE CODE WILL NOT FURTHER PROCEED IF CORRECT INPUT IS GIVEN
## IN THIS CODE continue AND break ARE USED WITHOUT COLON
## CONTINUE
# continue TELLS THAT THE CONDITION IS TRUE SO PROCEED FURTHER, HERE IT TELLS TO REPEAT THE CODE 
## WHILE break TELLS THAT THE CONDITION IS FALSE 
while True:
    n=int(input("enter x --"))
    if n<0:
        continue
    else :
        break

## HERE UNDERSCORE IS NECESSARY BECAUSE IT WILL STORE THE VALUE OF RUNNING COUNT
for _ in range(n):
    print("hi")